# .streamlit/secrets.toml
# Put this file in your repo at .streamlit/secrets.toml

sheet_url = "https://docs.google.com/spreadsheets/d/1dRMaH6G1bLzv-Bt1q5wEnZPC4ZylMCE7Dzcj1KAwURE/edit?usp=sharing"

[gcp_service_account]
type = "service_account"
project_id = "recommend-app-467714"
private_key_id = "d8d7a8d483f14a0eca86ddc934dfa46a5fb4e3ba"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDX/13k+01rkaiQ
jIl5D6wjCqpB3XddmsWE8uO64hWFWcJrhvu29oGTomwzJrCNHRxqIDt5O8qVq1//
J8bxRQfUBOpbBER2k+ttg5Gs2I4/f9YBtU5gxPgvzEtd/MfEyAJ+NfgesUY0PPJu
d71ROJvkermuWeLacaxS1DwMToX4mP8j93sY8qViRicWAdRgE3i6uxvXfw9G6gAl
LV9fG+auti1NVsygytQBkfPSTSWFtmo4wlrJQ052Qc6mFswmk4gNgmLN6xrZHRjg
Ot13UeK+QWBf/oR20DLQNhiu3YFV6It2f3UssPRJwmB5urnsnsxARHFXYuAcTzOj
/I5677oFAgMBAAECggEAK3D19KlxOPb22LmXJYS4KWUJ+Iy+5tHLs3E5SXsSensi
vccMZZAe3+8tBT2dCQiHkDWS2I9kr2Tj/fiFS72HNUZWzv7k+RdHZINvXzy/oThH
9Zh+HrrGsrBLIShHkkVqsPEQSbX8KWHvnTWSWx1ARzvCj/UOicIOdystt4jsa2KV
aXdequcHEuoxx0EUITbUOwXPvnr+cE8M3ElzP1gdXoMV+Sn97niN771h3Q8D4j0j
ufdIck26p5nz0Q6jYTAWU4MRvuj6ocYmWnDDPrr3aN8elW2QehqLhWYvxs5VKz5i
zP0KIOelXLZxo70BI3EDaIg1nfUszDCxhfFBrsE4mQKBgQDrORiGC2XIlE1a/zmo
nUYdNIEU+IKHctLVNbRN4nty+zZRgkMt/PgW/o25m3UiwC4e/LxFkKzYC+yVzQax
92elgJy3Phg37F1i047LEyMK9yEi7HXW+1RwdYIJriuCqkGLQ6cQt1Izqxb247pr
LDmkajivzqAJIDwrbvBbhsEgjQKBgQDrE4pgIxwqUKn2nrEl6fzF79qUpdxnIorG
hArXaJXuP5LdEL/02KvkB76Xeyi7GncrQi4xCrCEsas1+6FrvyACCqnGz8giqK2W
cp4LnPR7KnmghLv6gzzCurGgnc4BzkRAlLyRWCsUQ7gI8SveilwFNc9ZkEgTj3rT
SeMdGUVNWQKBgQCiBLjMk4svJl9F32iCqJnDwgdrP2UBEOkBrLUdtHNdloUqjXPi
eE0V4Y4TG24KWp8p/uFbdTRot4XlBMyoxoWgrL7FRML/uhH04U2IuQy5H9G2MXNV
edYGhBnmuw4DOWxeFWI8lFjNd/ogYmlkKpklk3iqN8NppcdsD0UFdgMOfQKBgQCO
rkOU6nqT7HXc7KEVJBp6gYSoKKvIJZ0ZtNdnu2EVRJz9dMct870RIOo7w1MLjZq7
NOYYeiZ9w+DpWRu27ECfPJ2jwEX3U25ZHKR05AU4JKXCGg6GlNVyVCKwHFgHnIys
rhpuFZfAKwIu20MHRe9ociqyb/JvfOzOBdDFvqrjsQKBgFgfXRo4nHXkOJURMjyY
ec0kzbCOLtTT9KWO6aQ/cOCWElERNf/blRQOEolfgiok0uOX4OKbLQxnrosXJYe5
y29Fz+SnYcWjQuh3lZgTDGls+oQQqNCrOO36E0AXZx8bExw0rzozb/yDP7oxON6C
RBeRZK73aV2bEV3Zu3Sl2qi3
-----END PRIVATE KEY-----"""
client_email = "recommend-app-account@recommend-app-467714.iam.gserviceaccount.com"
client_id = "109642732667874590091"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/recommend-app-account%40recommend-app-467714.iam.gserviceaccount.com"
